### ISSUE TITLE
missing documentation?

### ISSUE THREAD

**Issue by randomgambit** [matthieugomez/statar#12]
Hi Matthieu,

Thanks for this super helpful package (can you write one for Python and Pandas as well ? :) )

More seriously, I see that the documentation mentioned in the introductory page https://github.com/matthieugomez/vignettes/vector.Rmd is missing. 

Are you changing the docs right now?

Thanks!

**Comment by matthieugomez** [comment]
The docs are in the vignette folder. I think there is a statar missing in your link. Did you get this link from somewhere?

**Comment by randomgambit** [comment]
oh ok, weird now it works! yes from your own start github page!
