### ISSUE TITLE
clarify what is the purpose of tlag tlead?

### ISSUE THREAD

**Issue by randomgambit** [matthieugomez/statar#13]
Hi Matthieu,

I am reading your documentation about `tlag` and `tlead` and I dont get what they are supposed to do. Of course, I know the `L.` and `F.` operator in Stata but why are you saying that your function applies to any vector? It is not possible to shift any column with `dplyr` already?

**Comment by matthieugomez** [comment]
tlag/tlead a vector with respect to a number of periods, not with respect to the number of rows. Suppose you have a time variable with missing date(like `[1992, 1994]`), this matters.

**Comment by randomgambit** [comment]
got it
