### ISSUE TITLE
Error: StatBinmean was built with an incompatible version of ggproto.

### ISSUE THREAD

**Issue by jonathandroth** [matthieugomez/statar#14]
When trying to run ggplot with stat_binmean(), I get the following error

```
Error: StatBinmean was built with an incompatible version of ggproto.
Please reinstall the package that provides this extension.
```

I've tried re-installing the following packages:

devtools::install_github('slowkow/ggrepel')
devtools::install_github('hadley/ggplot2')
devtools::install_github('thomasp85/ggforce')
devtools::install_github('thomasp85/ggraph')

Thanks!

**Comment by matthieugomez** [comment]
Hi,
Could you try this?
https://github.com/dkahle/ggmap/issues/122
