### ISSUE TITLE
Error in count_combinations function

### ISSUE THREAD

**Issue by DavidArenburg** [matthieugomez/statar#2]
[This line](https://github.com/matthieugomez/statar/blob/master/R/count_combinations.R#L34) 

```r
setorder(dt, c("id", "count_across", "count_within"), order = c(1,1,-1))
```

Should be changed either to 

```r
setorderv(dt, c("id", "count_across", "count_within"), order = c(1,1,-1))
```
Or to

```r
setorder(dt, id, count_across, -count_within)
```

See [this SO question](http://stackoverflow.com/questions/30143718/error-in-count-combinations-in-statar) for reference

**Comment by matthieugomez** [comment]
Thank you! Corrected

**Comment by DavidArenburg** [comment]
I saw you rewrote the whole thing in`dplyr` :S quite disappointing...

**Comment by matthieugomez** [comment]
It's not a good function anyway
