### ISSUE TITLE
Wrap tables in statascii

### ISSUE THREAD

**Issue by gvelasq2** [matthieugomez/statar#20]
We should reimplement an updated `wrap_tbl()` function to wrap tables when the table width is longer than the console width. This should optimally repeat the first column of output when wrapping is necessary.

Example code to reproduce the issue:
`library(statar)`
`tab(mtcars, mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb)`

**Comment by matthieugomez** [comment]
I prefer to simply return a warning message in this case. https://github.com/matthieugomez/statar/commit/09dfd6e95608000fe3239bd8c53cc1194f0927b9
