### ISSUE TITLE
Move Imports to Suggests to reduce dependencies

### ISSUE THREAD

**Issue by jangorecki** [matthieugomez/statar#3]
A suggestion to move some Imports to Suggests. Imports are the deps which are required to installed to install statar, so it wise to make it short. If I want to use only few functions from your package it is quite big overhead. Maybe some of non-core processing related deps can be moved from Imports to Suggests? I'm not up to date with latest CRAN policies but it may only require to wrap their body into `if(require(`.

**Comment by matthieugomez** [comment]
You're right. I could remove lubridate, felm, stringdist, so that's better now.
