### ISSUE TITLE
Issue with sum_up function

### ISSUE THREAD

**Issue by will-gt** [matthieugomez/statar#37]
Dear Professor Matthieu Gomez,

I hope this email finds you well.  I’m a Stata user who has been using your statar package for 2 years. I wanted to reach out and thank you for developing such a useful tool.

However, I’ve recently encountered an issue when using the sum_up function. A warning message appears that says

Warning message:
There was 1 warning in `dplyr::summarize()`.
ℹ In argument: `describe(dplyr::across(), d = d, wtvar = wtvar, byvars = byvars)`.
Caused by warning:
! Using `across()` without supplying `.cols` was deprecated in dplyr 1.1.0.
ℹ Please supply `.cols` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 

I’m not sure how to fix this issue and was wondering if you could help out.

Thank you again for your contribution to the community!

**Comment by matthieugomez** [comment]
Thanks — I have just corrected it in the new version
