### ISSUE TITLE
Implement Conditional Join 

### ISSUE THREAD

**Issue by ywhuofu** [matthieugomez/statar#5]
Hi Matt,

I noticed you from my request for conditional join in data.table  [issue #829](https://github.com/Rdatatable/data.table/issues/829). I noticed you were proposing a solution. But the links seems no longer valid. Did you implement conditional join in your stater package? I read the manual but didn't find anything.

And thank you for this great package, it's extremely useful for someone from STATA!
Thank you!

**Comment by matthieugomez** [comment]
The solution I proposed is only for [rolling functions](https://github.com/matthieugomez/statar/blob/master/R/roll.R), not conditional join
