### ISSUE TITLE
Enrich `floor_date` function

### ISSUE THREAD

**Issue by ywhuofu** [matthieugomez/statar#6]
@matthieugomez  Could you add an additional parameter that determines start or end of the unit specified in `floor_date` function? 

An example would be:
```
d = as.Date('1992-03-15')
floor_date(d, 'month', 'end') # gives 1992-03-31
floor_date(d, 'month', 'start') # gives 1992-03-01
```
Thanks!

**Comment by matthieugomez** [comment]
The function is directly taken from hadley/lubridate, so you should try to make a request on this package. I have just rewritten it so that flooring to quarter is allowed.

Also note you can obtain the option `end` by

```
floor_date(d, 'month')+months(1) - days(1)
```

**Comment by matthieugomez** [comment]
Two points:
- ceiling_date in `lubridate` seems to do you want.  
- the newer version of lubridate [incorporates flooring wrt quarter](https://github.com/hadley/lubridate/pull/303), so floor_date is going to disappear form statar.
