### ISSUE TITLE
fill_gap() deprecated in 0.5.0, why?

### ISSUE THREAD

**Issue by yimingli** [matthieugomez/statar#7]
Hi. I updated to 0.5.0 today. But the `fill_gap()` function disappeared. Should I re-install the earlier version if I want to use it? Thanks!

**Comment by matthieugomez** [comment]
Hi. Sorry about that. I have just updated the [news ]https://github.com/matthieugomez/statar/blob/master/NEWS.md)

**Comment by matthieugomez** [comment]
Other people asked about it. So I've just added it back with a new syntax. 
```R
df %>% group_by(id1, id2) %>% fill_gap(time)
```
