### ISSUE TITLE
any reason that you removed functions for cleaning data.table?

### ISSUE THREAD

**Issue by lilchow** [matthieugomez/statar#8]
I really like many of the data.table cleaning functions such as setdiscard in an old version of this package. Could you let me know why you decided to remove these functions from the package? It kind of broke many of my previous codes. Thanks!

**Comment by matthieugomez** [comment]
I'm sorry I removed them.  I was under the impression these functions were not really useful.
Which one exactly did you use ? (I removed `setkeep`, `setdiscard`, `keep_if`, `discard_if`, `setmutate`).
As you may already know, you can just copy/paste back the source by looking at former commits (for instance [here](https://github.com/matthieugomez/statar/blob/b699d10c3579d6a2f3831f9f643610b76bd17614/R/set.R)).
FYI, I don't plan to remove anything from the package from now on (the package will soon be 1.0)
